#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Regenerate requirements.lock and automatically reapply manual edits
    that pip-compile would otherwise drop.

.DESCRIPTION
    Runs pip-compile against pyproject.toml with the same args the
    autogenerated header in requirements.lock declares, then patches
    `pywin32` with a `sys_platform == "win32"` marker so the Linux
    Docker build does not fail with
        ERROR: No matching distribution found for pywin32
    (pywin32 wheels are Windows-only; without the marker
    `pip install --require-hashes` rejects the resolution on Linux.)

    Run this whenever you bump a dep in pyproject.toml that affects
    the resolved tree (especially `mcp`, which pulls pywin32 in
    transitively on Windows).

.EXAMPLE
    .\scripts\refresh_lockfile.ps1
#>

[CmdletBinding()]
param()

function Write-Step { param([string]$Message) Write-Host "▶ $Message" -ForegroundColor Cyan }
function Write-Ok   { param([string]$Message) Write-Host "✓ $Message" -ForegroundColor Green }
function Write-Err  { param([string]$Message) Write-Host "✗ $Message" -ForegroundColor Red }

# Activate venv if present so `pip-compile` resolves.
if (Test-Path ".\.venv\Scripts\Activate.ps1") {
    & ".\.venv\Scripts\Activate.ps1"
}

pip-compile --version > $null 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Err "pip-compile is not installed. Install with: pip install pip-tools"
    exit 1
}

Write-Step "Running pip-compile..."
pip-compile --extra=web --generate-hashes --output-file=requirements.lock pyproject.toml
if ($LASTEXITCODE -ne 0) {
    Write-Err "pip-compile failed."
    exit 1
}
Write-Ok "Lockfile regenerated"

# Reapply the pywin32 platform marker. pip-compile strips comments and
# manual edits on each run, so we have to do this every time.
Write-Step "Applying pywin32 platform marker for Linux compatibility..."
$content = Get-Content requirements.lock -Raw
$before = 'pywin32==312 \'  # Update this if you bump pywin32.
$after  = 'pywin32==312 ; sys_platform == "win32" \'

# Match any pywin32==<ver> line that does NOT already carry the marker.
$pattern = '(?m)^pywin32==(?<v>[^\s;]+) \\'
$replacement = 'pywin32==${v} ; sys_platform == "win32" \'

if ($content -match $pattern) {
    if ($content -match 'pywin32==[^\s]+ ; sys_platform') {
        Write-Ok "Marker already present, nothing to do"
    } else {
        $patched = [regex]::Replace($content, $pattern, $replacement)
        Set-Content -Path requirements.lock -Value $patched -NoNewline
        Write-Ok "Applied sys_platform marker to pywin32"
    }
} else {
    Write-Ok "No pywin32 entry in lockfile (Linux-compiled?) — nothing to patch"
}

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  Lockfile refresh complete" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  git diff requirements.lock        # review changes" -ForegroundColor White
Write-Host "  docker build .                    # smoke-test the Linux build" -ForegroundColor White
Write-Host "  git add requirements.lock && git commit -m 'chore(deps): refresh lockfile'" -ForegroundColor White
Write-Host ""
