#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Regenerate requirements.lock and strip Windows-only entries that
    pip-compile would otherwise leave in.

.DESCRIPTION
    Runs pip-compile against pyproject.toml with the same args the
    autogenerated header in requirements.lock declares, then REMOVES
    the `pywin32` entry entirely. The Linux Docker build does
        pip install --require-hashes --no-deps -r requirements.lock
    and that combination does NOT reliably honor environment markers
    on pywin32 — pip queries PyPI for a Linux wheel that does not
    exist and fails the build. Dropping the entry is the only stable
    fix; mcp on Linux does not need pywin32.

    Run this whenever you bump a dep in pyproject.toml that affects
    the resolved tree (especially `mcp`, which pulls pywin32 in
    transitively on Windows).

.EXAMPLE
    .\scripts\refresh_lockfile.ps1
#>

[CmdletBinding()]
param()

function Write-Step { param([string]$Message) Write-Host "▶ $Message" -ForegroundColor Cyan }
function Write-Ok   { param([string]$Message) Write-Host "✓ $Message" -ForegroundColor Green }
function Write-Err  { param([string]$Message) Write-Host "✗ $Message" -ForegroundColor Red }

# Activate venv if present so `pip-compile` resolves.
if (Test-Path ".\.venv\Scripts\Activate.ps1") {
    & ".\.venv\Scripts\Activate.ps1"
}

pip-compile --version > $null 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Err "pip-compile is not installed. Install with: pip install pip-tools"
    exit 1
}

Write-Step "Running pip-compile..."
pip-compile --extra=web --generate-hashes --output-file=requirements.lock pyproject.toml
if ($LASTEXITCODE -ne 0) {
    Write-Err "pip-compile failed."
    exit 1
}
Write-Ok "Lockfile regenerated"

# Strip the pywin32 block. pip-compile re-introduces it on every run
# (it's a transitive of `mcp` on Windows), but the Linux Docker build
# rejects it because no Linux wheels exist, and environment markers
# are not reliably honored in `--require-hashes --no-deps` mode.
Write-Step "Stripping pywin32 block (Linux Docker build cannot resolve it)..."
$content = Get-Content requirements.lock -Raw

# A pywin32 block looks like:
#   pywin32==X.Y[ ; ...] \
#       --hash=sha256:... \
#       ...
#       --hash=sha256:...   (last hash line has no trailing backslash)
#       # via mcp           (optional)
# We match everything from the package header through the optional
# `# via ...` comment, then drop it. The trailing comment is the next
# top-level entry — we leave that alone.
$pattern = '(?ms)^pywin32==[^\r\n]*\r?\n(?:\s+--hash=[^\r\n]*\r?\n)+(?:\s*#\s*via[^\r\n]*\r?\n)?'

if ($content -match $pattern) {
    $replacement = @"
# pywin32 deliberately omitted. It's a Windows-only transitive of ``mcp``
# (provides Windows console handles). The Linux Docker build runs
#     pip install --require-hashes --no-deps -r requirements.lock
# and the combination ``--require-hashes`` + ``--no-deps`` + an environment
# marker on pywin32 has been observed to NOT skip the package on Linux
# in modern pip versions — pip queries PyPI for pywin32 wheels, finds
# none, and fails the build. Dropping the entry entirely is the
# reliable fix; mcp on Linux does not need pywin32, and Windows
# developers install via ``pip install -e .[web]`` (regular resolver)
# rather than via this lockfile.
"@
    $patched = [regex]::Replace($content, $pattern, $replacement + "`n")
    Set-Content -Path requirements.lock -Value $patched -NoNewline
    Write-Ok "Stripped pywin32 block"
} else {
    Write-Ok "No pywin32 block found in lockfile (already stripped) — nothing to do"
}

Write-Host ""
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  Lockfile refresh complete" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  git diff requirements.lock        # review changes" -ForegroundColor White
Write-Host "  docker build .                    # smoke-test the Linux build" -ForegroundColor White
Write-Host "  git add requirements.lock && git commit -m 'chore(deps): refresh lockfile'" -ForegroundColor White
Write-Host ""
